server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: dev
  cloud:
    config:
      server:
        git:
#          git repo config
          uri: https://github.com/salgu1998/config-yaml-file.git
#          username: username
#          password: password
#          uri: file:///Users/salgu/git/spring-cloud/git-local-repo