server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 1234
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/salgu/project/spring-cloud/native-file-repo
        git:
#          git repo config
          uri: https://github.com/salgu1998/config-yaml-file.git
#          username: username
#          password: password
#          uri: file:///Users/salgu/git/spring-cloud/git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh